#!/bin/bash

# Kamal IT Solutions - Hostinger Deployment Script
# This script helps you deploy your website to Hostinger

echo "=========================================="
echo "Kamal IT Solutions - Hostinger Deployment"
echo "=========================================="

# Check if GitHub repository exists
echo ""
echo "Step 1: Verifying GitHub Repository..."
if curl -s https://github.com/TSIDDIQUI1/KAMALITSOLUTIONS | grep -q "404 Not Found"; then
    echo "❌ Repository not found! Please create it at https://github.com/new"
    echo "   Repository name: KAMALITSOLUTIONS"
    exit 1
else
    echo "✅ Repository exists!"
fi

# Step 2: Deployment options
echo ""
echo "Step 2: Choose Your Hosting Option"
echo "==================================="
echo "1) Hostinger Shared Hosting (with Node.js)"
echo "2) Hostinger VPS"
echo "3) Netlify (Easiest - Free)"
echo "4) Vercel (Free, optimized for Node.js)"
echo ""

read -p "Enter option (1-4): " option

case $option in
    1)
        echo ""
        echo "=== Hostinger Shared Hosting Deployment ==="
        echo ""
        echo "📋 Manual Steps Required in Hostinger hPanel:"
        echo "==========================================="
        echo ""
        echo "1. Login to https://hpanel.hostinger.com"
        echo ""
        echo "2. Enable Node.js:"
        echo "   → Go to Advanced → Node.js"
        echo "   → Click 'Enable Node.js'"
        echo "   → Select Node.js version 18.x or higher"
        echo "   → Click 'Enable'"
        echo ""
        echo "3. Upload Files:"
        echo "   → Go to Files → File Manager"
        echo "   → Navigate to public_html/"
        echo "   → Upload all files from /Users/sid/Desktop/wb/KTS/"
        echo "   → Make sure package.json and server.js are in root"
        echo ""
        echo "4. Install Dependencies:"
        echo "   → Go to Advanced → Node.js"
        echo "   → Click 'Run npm install'"
        echo ""
        echo "5. Configure Application:"
        echo "   → Application Startup File: server.js"
        echo "   → Application Mode: Production"
        echo "   → Click 'Save Changes'"
        echo ""
        echo "6. Restart Application:"
        echo "   → Click 'Restart Application'"
        echo ""
        echo "7. Connect Domain:"
        echo "   → Go to Domains → Manage Domain"
        echo "   → Point to your Node.js app"
        echo ""
        echo "8. SSL Certificate:"
        echo "   → Go to SSL"
        echo "   → Click 'Install Free SSL'"
        echo ""
        echo "✅ Your website should be live at yourdomain.com!"
        ;;
        
    2)
        echo ""
        echo "=== Hostinger VPS Deployment ==="
        echo ""
        echo "📋 Manual Steps Required:"
        echo "=========================="
        echo ""
        echo "1. Login to https://hpanel.hostinger.com"
        echo ""
        echo "2. Get VPS IP from hPanel → VPS"
        echo ""
        echo "3. SSH into your VPS (use Terminal):"
        echo "   ssh root@YOUR_VPS_IP"
        echo ""
        echo "4. Run these commands on VPS:"
        echo "   ==========================================="
        echo "   # Update server"
        echo "   apt update && apt upgrade -y"
        echo ""
        echo "   # Install Node.js"
        echo "   curl -fsSL https://deb.nodesource.com/setup_18.x | bash -"
        echo "   apt-get install -y nodejs"
        echo ""
        echo "   # Install PM2"
        echo "   npm install -g pm2"
        echo ""
        echo "   # Create directory and clone"
        echo "   mkdir -p /var/www"
        echo "   cd /var/www"
        echo "   git clone https://github.com/TSIDDIQUI1/KAMALITSOLUTIONS.git"
        echo "   cd KAMALITSOLUTIONS"
        echo ""
        echo "   # Install dependencies"
        echo "   npm install --production"
        echo ""
        echo "   # Start app with PM2"
        echo "   pm2 start server.js --name 'kamal-it-solutions'"
        echo "   pm2 startup"
        echo "   pm2 save"
        echo "   ==========================================="
        echo ""
        echo "5. Configure Domain DNS:"
        echo "   → Add A record: @ → YOUR_VPS_IP"
        echo "   → Add A record: www → YOUR_VPS_IP"
        echo ""
        echo "6. Setup Nginx (optional but recommended):"
        echo "   apt install nginx"
        echo "   # Create /etc/nginx/sites-available/kamal-it-solutions"
        echo "   # Configure proxy to localhost:3000"
        echo ""
        echo "7. SSL Certificate:"
        echo "   apt install certbot python3-certbot-nginx"
        echo "   certbot --nginx -d yourdomain.com -d www.yourdomain.com"
        echo ""
        ;;
        
    3)
        echo ""
        echo "=== Netlify Deployment (Recommended) ==="
        echo ""
        echo "Step 1: Go to https://netlify.com"
        echo ""
        echo "Step 2: Click 'Add new site' → 'Import an existing project'"
        echo ""
        echo "Step 3: Connect GitHub and select 'KAMALITSOLUTIONS'"
        echo ""
        echo "Step 4: Configure:"
        echo "   → Build command: (leave empty)"
        echo "   → Publish directory: public"
        echo ""
        echo "Step 5: Click 'Deploy site'"
        echo ""
        echo "Step 6: Add Custom Domain:"
        echo "   → Go to Domain Management"
        echo "   → Add your domain"
        echo "   → Update DNS at Hostinger"
        echo ""
        echo "✅ Netlify will provide you with deployment URL!"
        ;;
        
    4)
        echo ""
        echo "=== Vercel Deployment (Excellent for Node.js) ==="
        echo ""
        echo "Step 1: Install Vercel CLI:"
        echo "   npm i -g vercel"
        echo ""
        echo "Step 2: Deploy from project folder:"
        echo "   cd /Users/sid/Desktop/wb/KTS"
        echo "   vercel"
        echo ""
        echo "Step 3: Follow prompts:"
        echo "   → Set up and deploy? Yes"
        echo "   → Which scope? Your account"
        echo "   → Link to existing project? No"
        echo "   → Project name: KAMALITSOLUTIONS"
        echo "   → Directory? ."
        echo "   → Want to modify settings? No"
        echo ""
        echo "Step 4: Production deployment:"
        echo "   vercel --prod"
        echo ""
        echo "Step 5: Add Custom Domain:"
        echo "   → Go to https://vercel.com/dashboard"
        echo "   → Select project → Settings → Domains"
        echo "   → Add your domain"
        echo ""
        echo "✅ Your website will be live on Vercel!"
        ;;
esac

echo ""
echo "=========================================="
echo "Deployment instructions complete!"
echo "=========================================="
echo ""
echo "📚 For detailed instructions, see:"
echo "   /Users/sid/Desktop/wb/KTS/GITHUB_DEPLOYMENT.md"
echo ""

